// "Browse packs" UI on the setup screen (consensustrivia.com + gradwritetrivia.org).
//
// PACK_CATALOG is regenerated by scrape_packs.py — see CLAUDE.md. Re-run
// the scraper when consensustrivia.com adds new packs. GRADWRITE_CATALOG is
// maintained by hand (the Gradwrite site is small and rarely changes) and is
// deliberately a separate const so pasting fresh scraper output over
// PACK_CATALOG can't wipe it.
//
// consensustrivia.com serves its pack PDFs with NO CORS header, so a browser
// on the live (GitHub Pages) site can't read the bytes via a plain fetch(). We
// relay through our own Cloudflare Worker (PACK_PROXY_BASE — see
// workers/pack-proxy/) which re-emits the pack with permissive CORS.
// gradwritetrivia.org sends `Access-Control-Allow-Origin: *`, so its packs are
// fetched directly (directCors below) with the relay chain as a fallback.
//
// fetchWithFallback walks a list of attempts: direct fetch (when the source
// allows it), our Worker relay, then the free public proxies as a legacy
// fallback. If every fetch path fails (e.g. the Worker is unset or over its
// daily quota and the public proxies are down), the caller degrades to a
// plain manual-download link — see renderManualFallback.

import { escapeHtml } from '../util/escape.js';
import { looksLikePdfOrZip } from '../parser/zip.js';
import { parsePdf, processZipBuffer } from '../loader.js';

export const PACK_CATALOG = [
  // Post-Secondary
  { level: 'post-secondary', season: '2024-25', tournament: 'Late Fall Tournament', dir: '2025-t1-ps', filePrefix: 'Consensus 2024-25 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2024-25', tournament: 'Qualifier', dir: '2025-t2-ps', filePrefix: 'Consensus 2024-25 T2 PS', packCount: 11 },
  { level: 'post-secondary', season: '2024-25', tournament: 'Championship', dir: '2025-t3-ps', filePrefix: 'Consensus 2024-25 T3 PS', packCount: 18 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Late Fall Tournament', dir: '2024-t2-ps', filePrefix: 'Consensus 2023-24 T2 PS', packCount: 10 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Qualifier', dir: '2024-t3-ps', filePrefix: 'Consensus 2023-24 T3 PS', packCount: 11 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Championship', dir: '2024-t4-ps', filePrefix: 'Consensus 2023-24 T4 PS', packCount: 11 },
  { level: 'post-secondary', season: '2023-24', tournament: 'Summer Open', dir: '2024-t1-open', filePrefix: 'Consensus 2023-24 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Season Opener', dir: '2023-t1-ps', filePrefix: 'Consensus 2022-23 T1 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Winter Tournament', dir: '2023-t2-ps', filePrefix: 'Consensus 2022-23 T2 PS', packCount: 10 },
  { level: 'post-secondary', season: '2022-23', tournament: 'Summer Open', dir: '2023-t3-open', filePrefix: 'Consensus 2022-23 T3 PS', packCount: 11 },
  // High School
  { level: 'high-school', season: '2024-25', tournament: 'Late Fall Tournament (Junior)', dir: '2025-t1-jr', filePrefix: 'Consensus 2024-25 T1 JR', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Late Fall Tournament', dir: '2025-t1-hs', filePrefix: 'Consensus 2024-25 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Qualifier (B)', dir: '2025-t2-hs-b', filePrefix: 'Consensus 2024-25 T2 HS B', packCount: 10 },
  { level: 'high-school', season: '2024-25', tournament: 'Qualifier', dir: '2025-t2-hs', filePrefix: 'Consensus 2024-25 T2 HS', packCount: 11 },
  { level: 'high-school', season: '2024-25', tournament: 'Championship', dir: '2025-t3-hs', filePrefix: 'Consensus 2024-25 T3 HS', packCount: 18 },
  { level: 'high-school', season: '2023-24', tournament: 'Season Opener (Junior)', dir: '2024-t1-jr', filePrefix: 'Consensus 2023-24 T1 JR', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Season Opener', dir: '2024-t1-hs', filePrefix: 'Consensus 2023-24 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Late Fall Tournament', dir: '2024-t2-hs', filePrefix: 'Consensus 2023-24 T2 HS', packCount: 10 },
  { level: 'high-school', season: '2023-24', tournament: 'Qualifier', dir: '2024-t3-hs', filePrefix: 'Consensus 2023-24 T3 HS', packCount: 11 },
  { level: 'high-school', season: '2023-24', tournament: 'Championship', dir: '2024-t4-hs', filePrefix: 'Consensus 2023-24 T4 HS', packCount: 15 },
  { level: 'high-school', season: '2022-23', tournament: 'Season Opener', dir: '2023-t1-hs', filePrefix: 'Consensus 2022-23 T1 HS', packCount: 10 },
  { level: 'high-school', season: '2022-23', tournament: 'Winter Qualifier', dir: '2023-t2-hs', filePrefix: 'Consensus 2022-23 T2 HS', packCount: 10 },
  { level: 'high-school', season: '2022-23', tournament: 'Championship', dir: '2023-t3-hs', filePrefix: 'Consensus 2022-23 T3 HS', packCount: 12 },
];

// Gradwrite packs (gradwritetrivia.org). `source: 'gradwrite'` switches the
// URL/filename builders below; `directCors: true` because the site serves
// packs with `Access-Control-Allow-Origin: *`. Spring 2024's two "XL" packs
// ride in `extraPacks` (they're extra content beyond the numbered packs).
export const GRADWRITE_CATALOG = [
  { source: 'gradwrite', level: 'post-secondary', season: '2024-25', tournament: 'Gradwrite Summer Open', dir: 'T4', filePrefix: 'Gradwrite-Summer-Open-2025', packCount: 10, directCors: true },
  { source: 'gradwrite', level: 'high-school', season: '2024-25', tournament: 'Gradwrite Spring', dir: 'T3', filePrefix: 'Gradwrite-Spring-2025', packCount: 10, directCors: true },
  { source: 'gradwrite', level: 'high-school', season: '2024-25', tournament: 'Consensus Gradwrite Fall', dir: 'T2', filePrefix: 'Consensus-Gradwrite-Fall-2024', packCount: 11, directCors: true },
  { source: 'gradwrite', level: 'high-school', season: '2023-24', tournament: 'Gradwrite Spring', dir: 'T1', filePrefix: 'Gradwrite-Spring-2024', packCount: 11, extraPacks: ['XL1', 'XL2'], directCors: true },
];

// Everything the browser renders: the scraped Consensus catalog + the
// hand-maintained Gradwrite one.
const FULL_CATALOG = [...PACK_CATALOG, ...GRADWRITE_CATALOG];

const PACK_SITE_BASE = 'https://www.consensustrivia.com';
const GRADWRITE_SITE_BASE = 'https://gradwritetrivia.org/Resources/Packs';
const IS_LOCAL_SERVER = location.protocol === 'http:' && (location.hostname === 'localhost' || location.hostname === '127.0.0.1');

// Our own Cloudflare Worker relay (workers/pack-proxy/). This is the reliable
// path on the live site. Fill in the deployed *.workers.dev URL after following
// workers/pack-proxy/README.md; leave '' to skip it and rely on the public
// proxies + manual-download fallback below.
const PACK_PROXY_BASE = 'https://consensus-pack-proxy.denisliu10.workers.dev';

// Ordered by preference: local dev proxy (serve.py) → our Worker → free public
// proxies. The public proxies are unreliable (rate limits / downtime) and only
// stay in the chain as a last resort before the manual-download fallback.
const CORS_PROXIES = [
  ...(IS_LOCAL_SERVER ? [(url) => `${location.origin}/proxy/${encodeURIComponent(url)}`] : []),
  ...(PACK_PROXY_BASE ? [(url) => `${PACK_PROXY_BASE}/?u=${encodeURIComponent(url)}`] : []),
  (url) => `https://api.codetabs.com/v1/proxy/?quest=${encodeURIComponent(url)}`,
  (url) => `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
  (url) => `https://corsproxy.io/?${encodeURIComponent(url)}`,
  (url) => `https://thingproxy.freeboard.io/fetch/${url}`,
];

function packPdfName(t, n) {
  return t.source === 'gradwrite' ? `${t.filePrefix}-Pack-${n}.pdf` : `${t.filePrefix} Pack ${n}.pdf`;
}
function packZipName(t) {
  return t.source === 'gradwrite' ? `${t.filePrefix}-All-Packs.zip` : `${t.filePrefix} Packs.zip`;
}
function packPdfUrl(t, n) {
  if (t.source === 'gradwrite') return `${GRADWRITE_SITE_BASE}/${t.dir}/${packPdfName(t, n)}`;
  return `${PACK_SITE_BASE}/${t.level}/packs/${t.dir}/${packPdfName(t, n)}`;
}
function packZipUrl(t) {
  if (t.source === 'gradwrite') return `${GRADWRITE_SITE_BASE}/${t.dir}/${packZipName(t)}`;
  return `${PACK_SITE_BASE}/${t.level}/packs/${t.dir}/${packZipName(t)}`;
}

async function fetchWithFallback(url, statusEl, { directCors = false } = {}) {
  const ATTEMPT_TIMEOUT_MS = 12000;
  // Direct attempt only for sources that send a CORS header (gradwrite) —
  // consensustrivia.com sends none, so there a plain cross-origin fetch can
  // never succeed and only logs a console error; every consensus attempt
  // goes through a relay (our Worker, then public proxies).
  const attempts = [...(directCors ? [(u) => u] : []), ...CORS_PROXIES];
  for (const makeProxy of attempts) {
    if (statusEl) statusEl.textContent = 'Downloading...';
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), ATTEMPT_TIMEOUT_MS);
    try {
      const r = await fetch(makeProxy(url), { signal: ctrl.signal });
      if (!r.ok) continue;
      const buffer = await r.arrayBuffer();
      if (looksLikePdfOrZip(buffer)) return buffer;
    } catch (e) { /* try next */ } finally {
      clearTimeout(timer);
    }
  }
  throw new Error('DOWNLOAD_FAILED');
}

// Last resort when every fetch path fails (Worker unset/over quota, public
// proxies down): show a plain browser-download link. The user saves the pack
// and drops it into the upload box — pack browsing keeps working with no infra.
function renderManualFallback(statusEl, url, filename) {
  if (!statusEl) return;
  const href = encodeURI(url);
  statusEl.className = 'pdf-status error';
  statusEl.innerHTML =
    `Automatic download is unavailable right now. ` +
    `<a href="${escapeHtml(href)}" target="_blank" rel="noopener">Download ${escapeHtml(filename)}</a>, ` +
    `then drop the file into the upload box above.`;
}

let activeBrowserLevel = 'post-secondary';

function renderBrowser() {
  const container = document.getElementById('browser-content');
  if (!container) return;
  const tournaments = FULL_CATALOG.filter(t => t.level === activeBrowserLevel);
  const bySeason = {};
  for (const t of tournaments) {
    if (!bySeason[t.season]) bySeason[t.season] = [];
    bySeason[t.season].push(t);
  }
  const seasons = Object.keys(bySeason).sort().reverse();
  const html = seasons.map(season => {
    const rows = bySeason[season].map((t) => {
      const tIdx = FULL_CATALOG.indexOf(t);
      const packBtns = [];
      const packLabels = [];
      for (let n = 1; n <= t.packCount; n++) packLabels.push(String(n));
      packLabels.push(...(t.extraPacks || []));
      for (const n of packLabels) {
        packBtns.push(`<button class="browser-pack-btn" data-action="pack" data-tidx="${tIdx}" data-pack="${n}" title="Pack ${n}">${n}</button>`);
      }
      const zipBtn = `<button class="browser-pack-btn zip" data-action="zip" data-tidx="${tIdx}" title="Download all packs as zip">All ZIP</button>`;
      return `
        <div class="browser-tournament">
          <div class="browser-tournament-name">${escapeHtml(t.tournament)}</div>
          <div class="browser-tournament-actions">${packBtns.join('')}${zipBtn}</div>
        </div>`;
    }).join('');
    return `<div class="browser-season"><div class="browser-season-label">${escapeHtml(season)} Season</div>${rows}</div>`;
  }).join('');
  container.innerHTML = html || '<div style="color:#666;font-size:0.9rem;">No tournaments available.</div>';
}

export function setupPackBrowser() {
  const toggle = document.getElementById('browse-toggle');
  if (toggle) {
    toggle.addEventListener('click', () => {
      const browser = document.getElementById('pack-browser');
      const opening = !browser.classList.contains('open');
      browser.classList.toggle('open', opening);
      toggle.textContent = opening
        ? 'Hide online pack browser'
        : 'Or browse packs from consensustrivia.com & gradwritetrivia.org';
      if (opening) renderBrowser();
    });
  }

  document.querySelectorAll('.browser-tab').forEach(tab => {
    tab.addEventListener('click', () => {
      activeBrowserLevel = tab.dataset.level;
      document.querySelectorAll('.browser-tab').forEach(t => t.classList.toggle('active', t === tab));
      renderBrowser();
    });
  });

  const content = document.getElementById('browser-content');
  if (content) {
    content.addEventListener('click', async (e) => {
      const btn = e.target.closest('.browser-pack-btn');
      if (!btn) return;
      const action = btn.dataset.action;
      const tIdx = parseInt(btn.dataset.tidx, 10);
      const tournament = FULL_CATALOG[tIdx];
      if (!tournament) return;
      const allBtns = document.querySelectorAll('.browser-pack-btn');
      allBtns.forEach(b => b.disabled = true);
      const statusEl = document.getElementById('pdf-status');
      // Hoisted so the catch can offer a manual-download link for this exact URL.
      let dlUrl = null;
      let dlName = null;
      try {
        if (action === 'pack') {
          const n = btn.dataset.pack; // "1".."18" or an extra like "XL1"
          dlUrl = packPdfUrl(tournament, n);
          dlName = packPdfName(tournament, n);
          if (statusEl) {
            statusEl.textContent = `Downloading Pack ${n}...`;
            statusEl.className = 'pdf-status';
          }
          const buffer = await fetchWithFallback(dlUrl, statusEl, { directCors: !!tournament.directCors });
          const sel = document.getElementById('zip-pack-select');
          if (sel) sel.style.display = 'none';
          await parsePdf(buffer, dlName);
        } else if (action === 'zip') {
          dlUrl = packZipUrl(tournament);
          dlName = packZipName(tournament);
          if (statusEl) {
            statusEl.textContent = `Downloading ${tournament.tournament} zip...`;
            statusEl.className = 'pdf-status';
          }
          const buffer = await fetchWithFallback(dlUrl, statusEl, { directCors: !!tournament.directCors });
          await processZipBuffer(buffer);
        }
      } catch (err) {
        if (err && err.message === 'DOWNLOAD_FAILED' && dlUrl) {
          renderManualFallback(statusEl, dlUrl, dlName);
        } else if (statusEl) {
          statusEl.textContent = 'Error: ' + err.message;
          statusEl.className = 'pdf-status error';
        }
      } finally {
        allBtns.forEach(b => b.disabled = false);
      }
    });
  }
}
